name: "Update DNS Records"

on:
  push:
    branches:
      - master
      # this is to prevent the workflow from running on PRs and other branches, which is important for security reasons

jobs:
  updateRecords:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: wget https://github.com/StackExchange/dnscontrol/releases/download/v3.15.0/dnscontrol-Linux
    - run: chmod +x dnscontrol-Linux
    - run: ./dnscontrol-Linux preview
      env:
        PACKETFRAME_TOKEN: ${{ secrets.PACKETFRAME_TOKEN }}
    - run: ./dnscontrol-Linux push
      env:
        PACKETFRAME_TOKEN: ${{ secrets.PACKETFRAME_TOKEN }}